services:
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tinyurl
    ports:
      - "5432:5432"
      
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
